name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
      run: |
        echo $ENCODED_STRING | base64 -di > app/scrcpy.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Server and Copy to Assets
      run: ./gradlew :server:copyServer

    - name: Build Release APK
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleScrcpyRelease

    - name: Extract Version Name
      id: extract_version
      run: |
        VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"' | tr -d "'")
        echo "Detected Version: $VERSION_NAME"
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

    - name: Rename APK
      run: |
        APK_PATH=$(find app/build/outputs/apk/scrcpy/release -name "*.apk" | head -n 1)
        
        NEW_NAME="scrcpy-QZRS-${{ env.VERSION_NAME }}-release.apk"
        
        mv "$APK_PATH" "$NEW_NAME"
        
        echo "APK renamed to: $NEW_NAME"
        echo "APK_FILENAME=$NEW_NAME" >> $GITHUB_ENV

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        # ä½¿ç”¨ ç‰ˆæœ¬å· + æ„å»ºç¼–å· ä½œä¸ºå”¯ä¸€ Tagï¼Œé˜²æ­¢è¢«è¦†ç›–
        tag_name: v${{ env.VERSION_NAME }}-${{ github.run_number }}
        name: Release v${{ env.VERSION_NAME }} (Build ${{ github.run_number }})
        body: |
          ğŸš€ æ­£å¼ç­¾åç‰ˆæœ¬: ${{ env.VERSION_NAME }}
          ğŸ”¢ æ„å»ºç¼–å·: ${{ github.run_number }}
          ğŸ”’ å·²ç­¾å (Release Signed)
          ğŸ“… æ„å»ºæ—¶é—´: ${{ steps.date.outputs.date }}
          sha: ${{ github.sha }}
        files: ${{ env.APK_FILENAME }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
